env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    - pkg install -y packetdrill
    - python3 --version
    - python3.7 -m venv venv
    - . venv/bin/activate
    - pip3.7 install -r scripts/requirements.txt
  test_script:
    - . venv/bin/activate
    - python3.7 scripts/run-tests.py --testplan testplans/testplan-freebsd.json --report_file junit.xml
  always:
    junit_artifacts:
      path: "*.xml"
      type: text/xml
      format: junit

macos_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install python3
    - python3 --version
    - python3 -m venv venv
    - . venv/bin/activate
    - pip3 install -r scripts/requirements.txt
  test_script:
    - NPLAB=1 scripts/install-packetdrill.sh
    - . venv/bin/activate
    - python3 scripts/run-tests.py --testplan testplans/testplan-macos.json --report_file junit.xml
  always:
    junit_artifacts:
      path: "*.xml"
      type: text/xml
      format: junit
