sudo: required

language: python

python: 3.7

os:
  - linux

matrix:
  include:
    - os: linux
      arch: amd64
      dist: xenial
    - os: linux
      arch: amd64
      dist: bionic

cache:
  directories:
    - packetdrill
    - venv

install:
  - sudo scripts/install-packetdrill.sh

script:
  - pip3 install -r scripts/requirements.txt
  - python3 scripts/run-tests.py --testplan testplans/testplan-linux.json --report_file junit.xml

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
